name: Test GDrive Service Account

on:
  workflow_dispatch:

jobs:
  test-sa:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Test Service Account
        env:
          SA_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
        run: |
          echo "$SA_JSON" > /tmp/sa.json
          rclone about gdrive: --drive-service-account-file /tmp/sa.json
