name: Test Rclone Upload

on:
  workflow_dispatch:

jobs:
  rclone-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Create service account JSON
        run: |
          echo "$GDRIVE_SERVICE_ACCOUNT" > /tmp/sa.json

      - name: Test service account
        run: |
          rclone about gdrive: --drive-service-account-file /tmp/sa.json

      - name: Upload file to Drive folder
        run: |
          rclone copy spotify.png gdrive:1EVIHk24_3C7DsCLcYoQOdrM_T11UrkWH/ --drive-service-account-file /tmp/sa.json -P
